import { test, expect } from '@playwright/test'

// A cold blog has no scene host: this journey guards the independent entry.
test('the shared menu preserves the blog header, reading position and form access', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/blog')
  await expect(page.locator('.blog-card').first()).toBeVisible()
  await page.locator('.blog-card').first().click()
  const reading = page.locator('.blog-root')
  await expect(page.locator('.blog-article')).toBeVisible()
  await reading.evaluate(el => { el.scrollTop = 350 })
  const scroll = await reading.evaluate(el => el.scrollTop)
  const header = page.locator('.site-header')
  const geometry = await header.boundingBox()
  const burger = header.locator('.site-header__burger')
  await burger.click()
  const surface = page.locator('.blog-surface')
  await expect(surface).toHaveAttribute('data-menu-state', 'open')
  await expect(page.locator('.site-menu-caption').first()).toBeVisible()
  await expect(page.locator('.site-menu-viewport')).toHaveAttribute('inert', '')
  await page.screenshot({ path: testInfo.outputPath('blog-menu-mobile.png'), animations: 'disabled' })
  expect((await page.locator('.site-menu-viewport').boundingBox())!.y).toBeGreaterThan(200)
  expect(await header.boundingBox()).toEqual(geometry)
  await page.keyboard.press('Escape')
  await expect(surface).toHaveAttribute('data-menu-state', 'closed')
  expect(await reading.evaluate(el => el.scrollTop)).toBe(scroll)
  await expect(burger).toBeFocused()
  await burger.click()
  await page.locator('.site-menu-layer .contact-trigger').click()
  await expect(page.locator('[role="dialog"]').first()).toBeVisible()
  await expect(burger).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(burger).toBeVisible()
  await page.setViewportSize({ width: 1400, height: 900 })
  await expect(burger).toBeHidden()
  await expect(header.locator('.audit-trigger')).toBeVisible()
  await expect(page.locator('.site-menu-viewport')).toHaveCSS('transform', 'none')
  await page.screenshot({ path: testInfo.outputPath('blog-header-desktop.png'), animations: 'disabled' })
})

// Exercise the warm document independently of the city's camera and display hit target.
test('the warm blog uses the same mobile menu without moving the scene behind it', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.waitForSelector('.app__scene .audit-trigger', { state: 'attached' })
  await page.evaluate(() => {
    history.pushState({}, '', '/blog')
    window.dispatchEvent(new PopStateEvent('popstate'))
  })
  const blog = page.locator('.blog-surface')
  await expect(blog).toBeVisible()
  await blog.locator('.site-header__burger').click()
  await expect(blog.locator('.site-menu-caption').first()).toBeVisible()
  await expect(blog.locator('.site-menu-viewport')).not.toHaveCSS('transform', 'none')
  await expect(page.locator('.app__scene')).toHaveAttribute('data-menu-state', 'closed')
  await blog.locator('.site-header__burger').click()
  await expect(blog).toHaveAttribute('data-menu-state', 'closed')
  await page.goBack()
  await expect(blog).toHaveCount(0)
})
