import { describe, expect, it } from 'vitest'
import { SITE_SETTINGS } from './generated/siteSettings'
import { siteSettingsProblems } from './invariants'
import { CONTACT_EMAIL, COPYRIGHT, SITE_PHONES } from './site'

/**
 * A guard on the guard.
 *
 * `siteSettings.collection.ts` proves the singleton invariant at build time and
 * `site.ts` reads `SITE_SETTINGS[0]` on the strength of it. This asserts the
 * same thing against the module that actually shipped, so an emitted file that
 * was hand-edited, half-written or generated by a relaxed audit fails here
 * rather than rendering `undefined` in the footer.
 */
describe('the shipped site settings', () => {
  it('is exactly one record', () => {
    expect(SITE_SETTINGS).toHaveLength(1)
  })

  it('satisfies the same invariants the build asserted', () => {
    expect(siteSettingsProblems(SITE_SETTINGS[0])).toEqual([])
  })
})

describe('the compatibility adapter', () => {
  it('exposes the generated values under the names the renderers use', () => {
    // SiteFooter and ContactSection import these three and nothing else. The
    // point of the adapter is that moving the data into the CMS did not touch
    // either of them.
    const settings = SITE_SETTINGS[0]
    expect(SITE_PHONES).toEqual(settings.phones)
    expect(CONTACT_EMAIL).toBe(settings.contactEmail)
    expect(COPYRIGHT).toBe(settings.copyright)
  })

  it('offers at least one dialable number', () => {
    expect(SITE_PHONES.length).toBeGreaterThan(0)
    for (const phone of SITE_PHONES) {
      expect(phone.tel, phone.display).toMatch(/^\+?[0-9]{6,20}$/)
    }
  })
})
