import { describe, expect, it } from 'vitest'
import { SITE_SETTINGS } from './generated/siteSettings'
import { siteSettingsProblems } from './invariants'
import { BOOKING_LABEL, BOOKING_URL, CONTACT_EMAIL, COPYRIGHT, LEGAL_DOCS, SITE_PHONES } from './site'

/**
 * A guard on the guard.
 *
 * `siteSettings.collection.ts` proves the singleton invariant at build time and
 * `site.ts` reads `SITE_SETTINGS[0]` on the strength of it. This asserts the
 * same thing against the module that actually shipped, so an emitted file that
 * was hand-edited, half-written or generated by a relaxed audit fails here
 * rather than rendering `undefined` in the footer.
 */
describe('the shipped site settings', () => {
  it('is exactly one record', () => {
    expect(SITE_SETTINGS).toHaveLength(1)
  })

  it('satisfies the same invariants the build asserted', () => {
    expect(siteSettingsProblems(SITE_SETTINGS[0])).toEqual([])
  })
})

describe('the compatibility adapter', () => {
  it('exposes the generated values under the names the renderers use', () => {
    // SiteFooter and ContactSection import these three and nothing else. The
    // point of the adapter is that moving the data into the CMS did not touch
    // either of them.
    const settings = SITE_SETTINGS[0]
    expect(SITE_PHONES).toEqual(settings.phones)
    expect(CONTACT_EMAIL).toBe(settings.contactEmail)
    expect(COPYRIGHT).toBe(settings.copyright)
  })

  it('passes the booking link through unchanged, absent included', () => {
    // Optional by design: the field arrived after the dataset, and there is no
    // sensible default for somebody else's calendar. `undefined` is the state
    // the contact dialog reads as "render no button".
    expect(BOOKING_URL).toBe(SITE_SETTINGS[0].bookingUrl)
    if (BOOKING_URL !== undefined) {
      // Asserted on SHAPE, never on a host. The client is changing scheduling
      // platform, and a test that named one would have to be edited to let
      // them — which is the coupling the field exists to remove.
      const url = new URL(BOOKING_URL)
      expect(url.protocol).toBe('https:')
      expect(url.pathname.length).toBeGreaterThan(1)
    }
  })

  it('always has words for the booking button, even with no link', () => {
    // The build resolves the fallback, so this is a string whether or not the
    // client has given us either field. `ContactSection` has no default of its
    // own, and this is what makes that safe.
    expect(BOOKING_LABEL).toBe(SITE_SETTINGS[0].bookingLabel)
    expect(BOOKING_LABEL.length).toBeGreaterThan(0)
  })

  it('offers at least one dialable number', () => {
    expect(SITE_PHONES.length).toBeGreaterThan(0)
    for (const phone of SITE_PHONES) {
      expect(phone.tel, phone.display).toMatch(/^\+?[0-9]{6,20}$/)
    }
  })
})

describe('the legal documents', () => {
  it('are exactly the three the site links to, each with a title and a body', () => {
    // The set is app composition (site.ts says why): the audit panel links two
    // and the consent banner the third. A generated module missing one would
    // fail `required()` at import; this pins the set the renderers assume.
    expect(Object.keys(LEGAL_DOCS).sort()).toEqual(['aviso', 'cookies', 'terminos'])
    for (const doc of Object.values(LEGAL_DOCS)) {
      expect(doc.title.length, doc.id).toBeGreaterThan(0)
      expect(doc.body.length, doc.id).toBeGreaterThan(0)
    }
  })
})
