import { describe, expect, it } from 'vitest'
import { TOWER_SCREEN } from './generated/towerScreen'
import { towerScreenProblems } from './invariants'
import { TOWER_SCREEN_CONTENT } from './tower'

/**
 * A guard on the guard, as `site.test.ts` is for the settings.
 *
 * `towerScreen.collection.ts` proves the singleton invariant at build time and
 * `tower.ts` reads `TOWER_SCREEN[0]` on the strength of it. This asserts the
 * same thing against the module that actually shipped, so an emitted file that
 * was hand-edited, half-written or generated by a relaxed audit fails here
 * rather than leaving the landmark's screen dark.
 */
describe('the shipped tower screen', () => {
  it('is exactly one record', () => {
    expect(TOWER_SCREEN).toHaveLength(1)
  })

  it('satisfies the same invariants the build asserted', () => {
    expect(towerScreenProblems(TOWER_SCREEN[0])).toEqual([])
  })

  it('has at least one slide, so the screen is never dark by omission', () => {
    expect(TOWER_SCREEN_CONTENT).toBe(TOWER_SCREEN[0])
    expect(TOWER_SCREEN_CONTENT.slides.length).toBeGreaterThan(0)
  })
})
