/**
 * The Services district's scene vocabulary: which authored object is which part
 * of the system.
 *
 * Keyed by object NAME rather than by anything read off the scene graph.
 * Traversal order is an accident of the export, and a mapping that depends on it
 * breaks silently the next time someone reorders the Blender outliner.
 *
 * What is deliberately NOT here:
 *
 * - **Copy.** It belongs to the CMS (`content/generated/districts.ts`), per
 *   DECISIONS §31. `serviceCopy.ts` splits a service `body` into the display's
 *   summary and detail.
 * - **The camera's decision.** Approach yaw and focus distance live in
 *   `scene/cityDistrictBindings.ts` beside every other scene-composition value,
 *   per DECISIONS §28.
 *
 * ## The district is four meshes now
 *
 * The 2026-09-06 re-export replaced fifteen nodes with four, and matched the
 * lab's `campus-vertigo` asset exactly. Gone: the shader ring, the five
 * connection wedges, the three focos, and the five per-service buildings. What
 * went with them is a whole subsystem — `flow/districtFlow.ts` and its fluid
 * shaders drew the ring and the wedges, and there is nothing left for them to
 * find, so they were deleted rather than left to warn once per missing name on
 * every load.
 *
 * The buildings were never selectable (plan 003 §6): a tap on any of them
 * enters, and after that they are scenery. That decision is what let this
 * export drop them from five to three without touching the interaction — there
 * was no building-to-service mapping to lose.
 */

/**
 * INTERIM, murcia-v6 (2026-09-11) until the services campus replaces this
 * district (docs/plans/024). v6 swapped the four `Edificios-servicios-*` nodes
 * for the campus, so the display now stands on campus names: the lake as its
 * plaza — its centre is 9 units from the old plaza's — and three of the
 * building's parts as the entry target. Nothing here survives the campus port.
 */

/**
 * The plaza — the display's anchor, the centre every radius is measured from,
 * and now the single projector as well.
 */
export const PLAZA_NODE_NAME = 'PARK_Water';

/**
 * The projectors the display appears to be generated by.
 *
 * ONE, and it is the plaza. Three separate `foco` nodes carried this until the
 * 2026-09-06 export removed them; the plaza is directly under the display and
 * reads as the thing casting it, which is what the focos were for. Kept as a
 * list because `servicesDisplay` builds one beam per entry and a future export
 * that brings real projectors back should only have to name them here.
 */
export const FOCO_NODE_NAMES: readonly string[] = [PLAZA_NODE_NAME];

/**
 * The buildings, as one entry target.
 *
 * Three meshes, and none of them means a service. They are what a tap enters
 * the district from and what stands around the plaza afterwards; the display is
 * the district's only interaction surface once it is open (plan 003 §6).
 *
 * Listed rather than derived from a prefix: a prefix match would also collect
 * the plaza, which is a floor and would put the hover glow on the ground.
 */
export const BUILDING_NODE_NAMES: readonly string[] = [
  'ARCH_Porcelain_White',
  'ARCH_Vertigo_Blue',
  'ARCH_Glazing_Opaque_Blue',
];

/**
 * Seconds for the display's fade, in and out.
 *
 * The entrance is no longer this: `displayReveal` materialises the panel over a
 * longer, staged clock and this is what LEAVING uses. Kept as one number because
 * the exit is deliberately undifferentiated — a departure that staged itself
 * would be asking for attention on the way out.
 */
export const ACTIVATION_DURATION = 0.9;

/**
 * The district's entrance, in seconds.
 *
 * The two run CONCURRENTLY: the motes start rising as the camera starts moving,
 * so the display is being built while the viewer is still travelling to it
 * rather than after they arrive to find it already there.
 *
 * `flight` is pinned rather than measured so the reveal can synchronise against
 * a fixed number. The app's own `CameraFlight` picks its duration from the
 * distance it has to cover, which is the right behaviour for a camera and the
 * wrong thing to hang an animation off — so this stays the reveal's contract and
 * the two are allowed to disagree by a little.
 *
 * `reveal` is provisional. A timing pass by eye is still owed.
 */
export const DISTRICT_ENTRANCE = { flight: 0.8, reveal: 2.8 };

/** What the display renders for one service. */
export interface DisplayContent {
  eyebrow: string;
  title: string;
  /** The scannable version. Short enough that switching feels immediate. */
  summary: string;
  /** The reading version, behind "saber más". */
  detail: string;
}

/** One service as the district needs it: content already split. */
export interface DistrictServiceView {
  id: string;
  title: string;
  summary: string;
  detail: string;
}

/**
 * What the display shows for a given state. Null means show nothing.
 *
 * Derived entirely from the index — there is no branch for "nothing selected",
 * because that state no longer exists. The counter tells the visitor there is a
 * finite set and where they are inside it (plan 003 §2).
 *
 * `label` is the district's, from the CMS, so the eyebrow reads the same here as
 * it did on the panel this display replaces.
 */
export function resolveDisplayContent(
  state: { districtActive: boolean; activeServiceIndex: number },
  services: readonly DistrictServiceView[],
  label: string,
): DisplayContent | null {
  if (!state.districtActive || services.length === 0) return null;

  const index = wrapIndex(state.activeServiceIndex, services.length);
  const service = services[index];

  return {
    eyebrow: `${label} · ${pad(index + 1)} / ${pad(services.length)}`,
    title: service.title,
    summary: service.summary,
    detail: service.detail,
  };
}

/**
 * Wraps an index into a list, in both directions.
 *
 * `count` is passed rather than read off a module constant because the service
 * list is content now: it is however many services the CMS published, and a
 * district with a service added is not a code change.
 */
export function wrapIndex(index: number, count: number): number {
  if (count <= 0) return 0;
  return ((index % count) + count) % count;
}

function pad(value: number): string {
  return value < 10 ? `0${value}` : String(value);
}
