/**
 * The Services district's scene vocabulary: which authored object is which part
 * of the system, and everything tuneable about the fluid that runs through it.
 *
 * Keyed by object NAME rather than by anything read off the scene graph.
 * Traversal order is an accident of the export, and a mapping that depends on it
 * breaks silently the next time someone reorders the Blender outliner.
 *
 * What is deliberately NOT here:
 *
 * - **Copy.** It belongs to the CMS (`content/generated/districts.ts`), per
 *   DECISIONS §31. `serviceCopy.ts` splits a service `body` into the display's
 *   summary and detail.
 * - **Which building is which service, and its accent.** That is scene
 *   composition and lives in `scene/cityDistrictBindings.ts` beside every other
 *   node-name binding, per DECISIONS §28.
 *
 * The lab (`prototypes/vertigo-lab`) carried all three in one file because it
 * had nowhere else to put them. Splitting them on the way across is the point:
 * an editor changing a paragraph must not be editing the same file as an artist
 * renaming a mesh.
 *
 * Buildings are NOT navigation. They are lit by whichever service is active and
 * they anchor the connection running in toward the ring; nothing here makes them
 * selectable (plan 003 §6, `docs/plans/010-services-district/`).
 */

/** The plaza — the display's anchor and the centre every radius is measured from. */
export const PLAZA_NODE_NAME = 'Edificios-servicios-plaza';

/**
 * The band the fluid shader is drawn on.
 *
 * ONE ring. An outer band (`...-anillo-shader-exterior`) existed briefly during
 * the lab's development and does not ship, so the two-ring hierarchy — outer
 * holding navy as a steady frame while the inner carried the accent — is gone
 * with it. The single ring takes the accent.
 *
 * Still called "interior" in Blender, a leftover from when there were two. Kept
 * verbatim: this constant's job is to match the authored name, not to be a good
 * name.
 *
 * It is a box-section band with real thickness, not a flat annulus. Its radius,
 * height and profile are art decisions living in Blender; this file only names
 * it, and `flow/districtFlow.ts` measures it.
 */
export const RING_NODE_NAME = 'Edificios-servicios-anillo-shader-interior';

/** The three projectors the display appears to be generated by. */
export const FOCO_NODE_NAMES: readonly string[] = [
  'Edificios-servicios-foco-001',
  'Edificios-servicios-foco-002',
  'Edificios-servicios-foco-003',
];

/**
 * The persistent base colour of the system while the district is active.
 *
 * The unselected connections hold it — which, with no outer ring, is the only
 * thing that does while the district is open. Dark enough to read as a resting
 * state beside five much brighter accents without competing with any of them.
 */
export const BASE_NAVY = 0x002761;

/**
 * Everything tuneable about the fluid, in one place.
 *
 * These were live on a debug panel in the lab and are fixed here — this repo has
 * no runtime GUI, and `config/environmentQueryOverrides.ts` is the established
 * way to make a number tuneable without a rebuild if one of them turns out to
 * need it.
 *
 * What is NOT here is per-mesh construction data (which band, which flow
 * direction, how long it waits to activate); that is derived from the geometry
 * and the role, and exposing it would only offer ways to break the system.
 */
export const DISTRICT_FLOW = {
  /** How fast the currents travel. */
  speed: 0.35,
  /**
   * How fine the currents are: waves per world unit.
   *
   * A frequency, and free to be fractional. It is NOT the thing that has to stay
   * whole — that is the per-element angular harmonic in `districtFlow`, the only
   * term that multiplies the angle and therefore the only one that can reopen
   * the seam. This scales the Cartesian field, which has no seam to open.
   */
  scale: 0.175,
  /** Overall brightness of the flowing material. */
  intensity: 1.05,
  /** How hard the currents bend each other. 0 is regular waves; too high is soup. */
  warp: 2,
  /** Seconds for a colour to travel from one service's accent to the next. */
  transition: 0.55,
  ringOpacity: 1,
  connectionOpacity: 1,
  /** Brightness of the bloom toward the band's inner edge. */
  edgeEmphasis: 0.9,
};

/**
 * Seconds for the district's entrance, shared by the flow reveal and the display
 * appearing so the two arrive together.
 */
export const ACTIVATION_DURATION = 0.9;

/**
 * How far into the entrance each part of the system starts, as a fraction of it.
 *
 * The system floods OUTWARD from the plaza: the ring lights first and the
 * connections follow it out toward the buildings. Two constants rather than a
 * timeline object — a stagger this small does not need a scheduler.
 */
export const ACTIVATION_STAGGER = {
  ring: 0,
  connection: 0.15,
};

/** What the display renders for one service. */
export interface DisplayContent {
  eyebrow: string;
  title: string;
  /** The scannable version. Short enough that switching feels immediate. */
  summary: string;
  /** The reading version, behind "saber más". */
  detail: string;
}

/** One service as the district needs it: content already split, accent resolved. */
export interface DistrictServiceView {
  id: string;
  title: string;
  summary: string;
  detail: string;
  accent: number;
}

/**
 * What the display shows for a given state. Null means show nothing.
 *
 * Derived entirely from the index — there is no branch for "nothing selected",
 * because that state no longer exists. The counter tells the visitor there is a
 * finite set and where they are inside it (plan 003 §2).
 *
 * `label` is the district's, from the CMS, so the eyebrow reads the same here as
 * it did on the panel this display replaces.
 */
export function resolveDisplayContent(
  state: { districtActive: boolean; activeServiceIndex: number },
  services: readonly DistrictServiceView[],
  label: string,
): DisplayContent | null {
  if (!state.districtActive || services.length === 0) return null;

  const index = wrapIndex(state.activeServiceIndex, services.length);
  const service = services[index];

  return {
    eyebrow: `${label} · ${pad(index + 1)} / ${pad(services.length)}`,
    title: service.title,
    summary: service.summary,
    detail: service.detail,
  };
}

/**
 * Wraps an index into a list, in both directions.
 *
 * `count` is passed rather than read off a module constant because the service
 * list is content now: it is however many services the CMS published, and a
 * district with a service added is not a code change.
 */
export function wrapIndex(index: number, count: number): number {
  if (count <= 0) return 0;
  return ((index % count) + count) % count;
}

function pad(value: number): string {
  return value < 10 ? `0${value}` : String(value);
}
