import * as THREE from 'three';
import { shellPerimeterPoints, type DisplayShellDimensions } from './displayShell';
import fragmentShader from '../shaders/reveal/fragment.glsl';
import vertexShader from '../shaders/reveal/vertex.glsl';

/**
 * The display's materialisation: motes leave the projectors, ride the beams up,
 * COLLECT INTO A MASS at the display's centre, hold there churning, and then open
 * outward onto the plate's outline before handing the shape to the panel.
 *
 * ## Why this exists at all, given plan 001 forbade it
 *
 * Plan 001 lists "particle transitions" under *Do NOT implement yet* and "particles
 * unless required internally by the shader experiment" under its non-goals. That gate
 * was lifted deliberately and by request: the display previously had no arrival, it
 * simply became opaque over 0.9 seconds, and the three projectors it is supposedly
 * generated by faded up on the same curve — which made them decoration aimed at
 * something that assembled itself. This is the smallest thing that makes the
 * projectors the cause rather than the accompaniment.
 *
 * That is a decision, not an oversight, and it is written here so a future reader
 * finds the reasoning next to the code rather than concluding the plan was ignored.
 *
 * ## The motes come from the FOCOS, even though they gather at the centre
 *
 * The obvious version has them simply appear in mid-air and coalesce. It looks fine
 * and it says the wrong thing: a display that assembles itself out of nothing does
 * not need three projectors pointed at it. Every mote is sourced at a foco and routed
 * through the beams' own convergence point before it reaches the mass, which keeps
 * the projectors causal, and it costs nothing — `servicesDisplay` already computes
 * both endpoints every time it lays the beams out.
 *
 * ## Why there is a mass at all
 *
 * The flow used to go from the beams straight onto the outline. It read well as
 * motion and said very little: a stream became a thin dotted rectangle, with no
 * moment anywhere showing the QUANTITY of material the display is made of. The mass
 * is that moment — the difference between "particles drew a shape" and "there was a
 * pile of stuff, and the display is what it became".
 *
 * ## A CHILD of the panel, like the plate
 *
 * The landing points are the plate's silhouette, which yaws and tilts with the panel.
 * As a child, they inherit both for free and can never drift out of register with the
 * edge they are drawing. The inverse conversion — three world-space projector
 * positions into panel space, once per frame — is the cheap direction, and it is the
 * only reason this module wants an `update` at all.
 *
 * ## It owns no clock
 *
 * `uProgress` is written from outside. Every phase, stagger and ease is a function of
 * that one number in `reveal.vert`, so the whole effect is scrubbable, reversible and
 * frame-rate independent without this file knowing what a second is. It also means
 * "latest state wins" (plan 003 §22) is free: retargeting the progress retargets the
 * animation, and there is no queue anywhere to drain.
 */

/** The reveal's palette. Exported so the debug panel reads these, not a second copy. */
export const REVEAL_COLORS = {
  /** Leaving the projector: the beam's own cyan, so the mote belongs to the beam. */
  from: 0x64d8f4,
  /**
   * Landed: the display's own graphite. The motes DARKEN as they settle.
   *
   * This was a pale near-white first, on the reasoning that particles glow. That is
   * the wrong instinct in this scene and it made them invisible: the background is
   * light grey `0xd3d3d3` and the ground lighter still, so a pale mote against them
   * has almost no contrast — the same trap that rules out additive blending here.
   *
   * Darkening is also the better story. The mote arrives as projector light and ends
   * as a piece of the object it just built, which is exactly what the colour now
   * says. Matched to the face's fringe rather than to its core, so a settled mote
   * sits a shade above the screen instead of vanishing into it.
   */
  to: 0x262b31,
} as const;

/**
 * How many motes. It has only ever gone up: 96, 220, 400, and now 900.
 *
 * Each rise came from the effect being asked to do more. It began as "a few motes
 * riding the beams", became "an outline legible enough to recognise the display's
 * shape", and now has to fill a VOLUME as well. That last one is what forced 900: a
 * count tuned for a perimeter spreads along a line, and the same number scattered
 * through a ball is a thin sprinkle — at 400 the mass read as dust rather than as a
 * quantity of anything.
 *
 * The outline got better in the process rather than worse. At 900 it is a fine
 * continuous line where 400 was a row of separate beads.
 *
 * Read together with the size, which came DOWN to 400 as this went up: many small
 * motes read as a drawn line, few large ones as a necklace.
 */
const PARTICLE_COUNT = 900;

/**
 * Mote size, in pixels-times-world-units — it is divided by view depth in the vertex
 * shader, so the number only means something once you divide it by a distance.
 *
 * 400 gives roughly 3.5px at the district camera's 115 units. Deliberately small,
 * and it came DOWN from 900 as the count went up: at 8px, 400 motes on a perimeter
 * overlap into a solid bead necklace, which reads as a decorative frame rather than
 * as a structure someone drew. Small and many reads as an outline.
 *
 * The arithmetic is worth keeping in view because the obvious number is wrong by an
 * order of magnitude: this is divided by view depth, so a plausible-looking 90 is
 * 0.78 of a pixel here — present, invisible, and indistinguishable from broken.
 *
 * Anything tuned here must be re-checked at the debug panel's distance extremes: the
 * same constant gives 8px at d=50 and 1.9px at d=210.
 */
const PARTICLE_SIZE = 400;

/**
 * How far in front of the plate's FRONT CAP the motes sit, in world units.
 *
 * Measured from `SHELL_FRONT_Z`, which is why that constant is exported rather than
 * re-derived: the plate's mesh is positioned at `-(thickness + FRONT_GAP)` but its
 * extrusion runs forward from there, so the surface the visitor sees is at
 * `-FRONT_GAP`. Reading the position instead of the cap puts the motes a whole plate
 * thickness too far back — inside the volume, where the cap depth-tests them away and
 * the effect renders nothing at all with no error anywhere.
 *
 * It must also stay non-zero: `depthWrite` is off here but `depthTest` is on, and a
 * mote exactly co-planar with a surface flickers against it.
 */
const FRONT_OFFSET = 0.08;

/**
 * Radius of the mass, world units, before the motes open into the outline.
 *
 * The plate is about 42 units across, so 7 makes the mass roughly a third of the
 * shape it becomes — big enough to read as a quantity of material, small enough that
 * the expansion into the outline is a clear change of state rather than a nudge.
 *
 * Live in the debug panel, because `aMass` is baked as a UNIT ball and scaled here:
 * radius is the one property of the mass that can be tuned without a rebuild.
 */
const MASS_RADIUS = 7;

/**
 * How far across the projector's face the motes start, world units.
 *
 * 15, against a plaza half-width of about 20, so they leave from most of its surface
 * without reaching the rim.
 *
 * This exists because the projector became the plaza. With three focos a mote could
 * start at a foco's centre and the three separate origins gave the rise its spread;
 * with one projector directly under the display, every mote would launch from a
 * single point on the plaza's axis and the whole ride would be one thin column. The
 * plaza is a 40-unit surface, so it should emit like one.
 */
const SOURCE_RADIUS = 15;

/**
 * How far the mass swirls across the whole clock, in radians.
 *
 * About a sixth of a turn at the median mote, sheared per mote so the layers slide
 * against each other rather than rotating as one rigid ball. Enough that the mass is
 * visibly alive while it holds still; at 2.2 it read as a vortex, which is a
 * different and much louder idea.
 *
 * 0 in the debug panel is the honest A/B — a completely still cloud — for deciding
 * whether the motion is earning anything.
 */
const MASS_CHURN = 1.0;

/**
 * Spreads the per-mote seed evenly over 0..1.
 *
 * Deterministic rather than `Math.random()`, and that is a requirement rather than a
 * preference: the reveal has to look identical every time it plays or the stagger,
 * the churn and the mass cannot be tuned — each replay would be a different effect.
 *
 * An irrational multiple is right HERE, where an evenly spread sequence with no
 * repeats is exactly what a stagger wants. It is wrong for the mass, which needs the
 * opposite property; see `hash` below.
 */
const GOLDEN_RATIO = 0.6180339887;

/**
 * Deterministic pseudo-random in 0..1, the classic sine hash.
 *
 * Used for the mass, where an irrational-multiple sequence is exactly the wrong tool:
 * those are quasi-regular by design, and regularity inside a cloud you can see
 * through renders as visible lattice structure. This is unstructured, and it still
 * returns the same value for the same index on every run, which is what lets the
 * effect be tuned by eye.
 */
function hash(n: number): number {
  const x = Math.sin(n * 127.1 + 311.7) * 43758.5453;
  return x - Math.floor(x);
}

export interface DisplayRevealOptions {
  /** The plate's dimensions — the outline the motes settle onto. */
  dimensions: DisplayShellDimensions;
  /** Where the plate's front face sits in panel space, so the motes land in front. */
  frontZ: number;
}

export interface DisplayReveal {
  readonly object: THREE.Points;
  readonly material: THREE.ShaderMaterial;
  /** The reveal clock, 0..1. The only thing that advances the animation. */
  setProgress(value: number): void;
  /** The three projector tops, in WORLD space. Converted here. */
  setSources(sources: readonly THREE.Vector3[], converge: THREE.Vector3): void;
  /** Re-scatters the landing points. Call whenever the plate's outline changes. */
  setDimensions(dimensions: DisplayShellDimensions, frontZ: number): void;
  /** Rebuilds the buffers. Disposes what it replaces. */
  setCount(count: number): void;
  dispose(): void;
}

export function createDisplayReveal(options: DisplayRevealOptions): DisplayReveal {
  let count = PARTICLE_COUNT;
  let dimensions = options.dimensions;
  let frontZ = options.frontZ;

  const material = new THREE.ShaderMaterial({
    vertexShader,
    fragmentShader,
    transparent: true,
    // These pass in front of the plate, the plaza and the buildings. Writing depth
    // would let one mote occlude the next and punch holes in whatever is behind
    // them, for no benefit — they are light, not surfaces.
    depthWrite: false,
    // OFF, and this one is not a preference either — it is the difference between
    // the effect rendering and rendering nothing at all.
    //
    // The motes fly from the projectors to the display, and the projectors sit below
    // and BEHIND the panel: their whole path lives at panel-local z between about
    // -19 and 0, which is behind the plate. So the moment the plate starts resolving
    // and writing depth — at 0.62 of the clock, while the fan is still running — the
    // object being built occludes every mote still on its way to build it.
    //
    // Turning depth off costs the one thing it was buying: a mote passing behind a
    // building is no longer hidden by it. That is a brief, minor artefact on a
    // 1.2-second effect, and it is arguably the correct reading anyway — these are
    // meant to be light in the air, not solids.
    //
    // Worth knowing how this presents, because it cost an hour: positions, sizes,
    // colours, attributes and uniforms all probe as perfectly correct, the draw call
    // is issued, no warning appears anywhere, and the screen stays empty.
    depthTest: false,
    // Normal rather than additive, and this is not a preference. The scene's
    // background is light grey, where additive saturates to white and the motes
    // disappear into it — the same rule `districtFlow` states for the ring.
    blending: THREE.NormalBlending,
    uniforms: {
      uSource0: { value: new THREE.Vector3() },
      uSource1: { value: new THREE.Vector3() },
      uSource2: { value: new THREE.Vector3() },
      uConverge: { value: new THREE.Vector3() },
      // World X and Z expressed in PANEL space. Two vectors rather than one radius,
      // because the motes hang off a panel tilted 45 degrees: offsetting them along
      // the panel's own axes would scatter them across a leaning plane instead of
      // across the plaza's flat top.
      uSpreadU: { value: new THREE.Vector3(1, 0, 0) },
      uSpreadV: { value: new THREE.Vector3(0, 0, 1) },
      uSourceRadius: { value: SOURCE_RADIUS },
      uMassCentre: { value: new THREE.Vector3(0, 0, frontZ + FRONT_OFFSET) },
      uMassRadius: { value: MASS_RADIUS },
      uChurn: { value: MASS_CHURN },
      uProgress: { value: 0 },
      uSize: { value: PARTICLE_SIZE },
      uOpacity: { value: 0.85 },
      uColorFrom: {
        value: new THREE.Color().setHex(REVEAL_COLORS.from, THREE.SRGBColorSpace),
      },
      uColorTo: {
        value: new THREE.Color().setHex(REVEAL_COLORS.to, THREE.SRGBColorSpace),
      },
    },
  });

  const object = new THREE.Points(buildGeometry(count, dimensions, frontZ), material);
  object.raycast = () => {};
  // After the panel (3). The motes are in front of everything they are assembling,
  // which is what a thing being delivered looks like.
  object.renderOrder = 4;
  // The bounding sphere is computed from the dummy `position` attribute, but every
  // real position is produced in the vertex shader from uniforms — so three's culling
  // has no idea where these actually are and would pop them out at the worst moment,
  // mid-flight between a projector and the panel.
  object.frustumCulled = false;

  /** Reusable, so a per-frame conversion allocates nothing. */
  const scratch = new THREE.Vector3();
  /** Panel-space origin, held so the spread basis can be a difference of positions. */
  const origin = new THREE.Vector3();

  return {
    object,
    material,

    setProgress(value) {
      material.uniforms['uProgress']!.value = THREE.MathUtils.clamp(value, 0, 1);
    },

    setSources(sources, converge) {
      // World -> panel space. `worldToLocal` mutates its argument, hence the scratch
      // vector and the copy out into the uniform rather than handing it the caller's.
      const parent = object.parent;
      if (!parent) return;

      for (let i = 0; i < 3; i += 1) {
        const source = sources[i] ?? sources[0];
        if (!source) continue;
        scratch.copy(source);
        parent.worldToLocal(scratch);
        (material.uniforms[`uSource${i}`]!.value as THREE.Vector3).copy(scratch);
      }

      scratch.copy(converge);
      parent.worldToLocal(scratch);
      (material.uniforms['uConverge']!.value as THREE.Vector3).copy(scratch);

      // The spread basis: world X and Z as DIRECTIONS in panel space.
      //
      // Derived by transforming a point and subtracting the transformed origin,
      // rather than by transforming the direction itself — `worldToLocal` applies the
      // full inverse including translation, so handing it a unit vector returns a
      // position, not a direction. Getting this wrong puts the whole scatter at a
      // fixed offset from the plaza instead of around it.
      scratch.set(0, 0, 0);
      parent.worldToLocal(scratch);
      origin.copy(scratch);

      scratch.set(1, 0, 0);
      parent.worldToLocal(scratch);
      (material.uniforms['uSpreadU']!.value as THREE.Vector3).copy(scratch).sub(origin);

      scratch.set(0, 0, 1);
      parent.worldToLocal(scratch);
      (material.uniforms['uSpreadV']!.value as THREE.Vector3).copy(scratch).sub(origin);
    },

    setDimensions(next, nextFrontZ) {
      dimensions = next;
      frontZ = nextFrontZ;
      object.geometry.dispose();
      object.geometry = buildGeometry(count, dimensions, frontZ);
      // The mass shares the outline's plane by definition, so it moves with it. Left
      // behind, the motes would gather a plate-thickness off the shape they then open
      // into, and the expansion would read as a lurch rather than as a bloom.
      (material.uniforms['uMassCentre']!.value as THREE.Vector3).set(
        0,
        0,
        frontZ + FRONT_OFFSET,
      );
    },

    setCount(next) {
      const clamped = Math.max(3, Math.floor(next));
      if (clamped === count) return;
      count = clamped;
      object.geometry.dispose();
      object.geometry = buildGeometry(count, dimensions, frontZ);
    },

    dispose() {
      // Geometry AND material: this module built both, like `displayShell` and unlike
      // `districtFlow`, which draws on the loaded model's meshes.
      object.geometry.dispose();
      material.dispose();
    },
  };
}

/**
 * One mote per landing point, dealt round-robin to the three beams.
 *
 * Round-robin rather than three contiguous arcs, and that is a real choice: giving
 * each projector a third of the perimeter would have each beam feed the segment
 * nearest it, which is tidier and reads as three separate deliveries. Interleaving
 * means all three beams contribute across the whole outline, so the silhouette
 * completes everywhere at once instead of in three sectors.
 */
function buildGeometry(
  count: number,
  dimensions: DisplayShellDimensions,
  frontZ: number,
): THREE.BufferGeometry {
  const perimeter = shellPerimeterPoints(dimensions, count);

  const positions = new Float32Array(count * 3);
  const targets = new Float32Array(count * 3);
  const mass = new Float32Array(count * 3);
  const beams = new Float32Array(count);
  const seeds = new Float32Array(count);

  const z = frontZ + FRONT_OFFSET;

  for (let i = 0; i < count; i += 1) {
    const point = perimeter[i % perimeter.length];
    if (!point) continue;

    targets[i * 3 + 0] = point.x;
    targets[i * 3 + 1] = point.y;
    targets[i * 3 + 2] = z;

    // --- the mass, as a point in the UNIT ball -----------------------------
    //
    // HASHED, not a Fibonacci sphere, and the mistake is worth recording.
    //
    // A Fibonacci lattice is the right tool for spreading points over a SURFACE, and
    // it was the obvious choice here for exactly that reason. But this is a volume
    // you can see through, and its regular golden-angle azimuth is plainly visible
    // from outside as sunflower spirals — the mass rendered as a small galaxy with
    // clean arms. That was first blamed on the churn, and it survived setting the
    // churn to ZERO, which is what gave it away: the structure was in the
    // distribution all along, not in the motion.
    //
    // Three independent hashes give a genuinely unstructured cloud while staying
    // deterministic, which this module requires — the reveal has to look identical on
    // every replay or none of it can be tuned by eye.
    const u1 = hash(i * 3);
    const u2 = hash(i * 3 + 1);
    const u3 = hash(i * 3 + 2);

    // `1 - 2u` for the height with a free azimuth is the unbiased way to pick a
    // direction. Choosing two angles uniformly instead bunches points at the poles.
    const up = 1 - 2 * u1;
    const ring = Math.sqrt(Math.max(0, 1 - up * up));
    const theta = u2 * Math.PI * 2;

    // DENSE CORE, SOFT EDGE. Uniform-in-a-ball wants `u ** (1/3)`, which looks
    // hollow — most of a sphere's volume is near its surface, so an even fill reads
    // as a shell. A larger exponent pulls motes inward; 0.7 leaves a clear core with
    // the population thinning toward the edge, which is what makes it read as a mass
    // rather than as a bubble.
    const radius = Math.pow(u3, 0.7);

    mass[i * 3 + 0] = Math.cos(theta) * ring * radius;
    mass[i * 3 + 1] = up * radius;
    mass[i * 3 + 2] = Math.sin(theta) * ring * radius;

    beams[i] = i % 3;
    // Deterministic rather than `Math.random()`: the reveal should look identical
    // every time it plays, and a stagger that reshuffles per visit is a stagger
    // nobody can tune. The golden ratio spreads the sequence evenly without ever
    // repeating over any count this module will use.
    seeds[i] = (i * GOLDEN_RATIO) % 1;

    // The dummy `position` three requires. Never read by the shader — every real
    // position comes from the two lerps — but the attribute must exist and must be
    // the right length or the draw call has no vertex count.
    positions[i * 3 + 0] = 0;
    positions[i * 3 + 1] = 0;
    positions[i * 3 + 2] = 0;
  }

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  geometry.setAttribute('aTarget', new THREE.BufferAttribute(targets, 3));
  geometry.setAttribute('aMass', new THREE.BufferAttribute(mass, 3));
  geometry.setAttribute('aBeam', new THREE.BufferAttribute(beams, 1));
  geometry.setAttribute('aSeed', new THREE.BufferAttribute(seeds, 1));

  return geometry;
}
